feat: first pass on parsing script and intro content
ciandt-centelha/architecture-guidebook pull request #1
Opened 2024-08-15 01:44 UTC by cgallati

Sets up the `architecture-academy-extracts` directory to contain content from architecture academy slides. This can be used as source material for the actual Architecture Guidebook content.

- `slides-extractor`: A python package that, when run, parses all the json files in `/json` into markdown files in `/md`. Can handle text, tables, and images.

2024-08-15 16:07 UTC, timpepper-ciandt requested changes

2024-08-15 16:07 UTC, timpepper-ciandt commented on architecture-academy-extracts/README.md
> +     python save_json.py
Is this supposed to be `python url_to_json_file.py`? I don't see a `save_json.py` in your changes.

2024-08-15 16:07 UTC, timpepper-ciandt commented on architecture-academy-extracts/slides-extractor/main.py
> +def parse_paragraph_marker(paragraph_marker, nesting_level=0):
Is the nesting_level necessary? I see it's not being used, but I did see you noted a potentially related problem with bulleted lists in the README, and understand it could be used in the future

2024-08-15 19:13 UTC, cgallati commented on architecture-academy-extracts/slides-extractor/main.py
> +def parse_paragraph_marker(paragraph_marker, nesting_level=0):
It's not necessary, just left over from my attempt to get bullets working. I'll remove for now. 

I'm thinking of switching all of the markdown writing to a library instead of doing it all manually, so it likely won't be needed in v2.

2024-08-15 19:35 UTC, timpepper-ciandt commented on architecture-academy-extracts/slides-extractor/main.py
> +def parse_paragraph_marker(paragraph_marker, nesting_level=0):
That'll be neat! I'll be interested in seeing which library you pick for that.

2024-08-16 13:37 UTC, Rodhlann approved these changes

2024-08-16 13:38 UTC, timpepper-ciandt approved these changes
Approved with the wrong account! 😆 Looks great man awesome work

2024-08-16 15:45 UTC, marwanciandt commented
Great start!!

Future enhancements might include 
- adding cli args parsing e.g folder location, input/output format. 
- Auto fetching of the slides' json as mentioned in the README once we have a work around GCP project setup and authentication.

2024-08-16 15:46 UTC, marwanciandt approved these changes

2024-08-16 16:24 UTC, cgallati commented
I goofed and accidentally integrated a commit from my work in progress branch to add a markdown util lib. Not even sure that the script works in the current version. 

I'll fail foward and get this PR updated with the markdown lib in a working state, maybe a test or two as well 😅

2024-08-27 14:39 UTC, merged